export const cases = [
  {
    slug: 'ai-customer-service',
    number: '002',
    title: '重复的问题交给AI，需要判断的交给人。',
    shortTitle: 'AI客服：从知识问答到人工接手',
    description: '在虚拟数码店铺场景中，用飞书、Dify与FastAPI连接知识问答、人工工单和回复回传。记录错误回复、处理方式与测试边界。',
    status: '个人实验 · 测试环境跑通',
    tags: ['AI客服', '知识库', '人工接手'],
    summary: '用飞书连接知识库与人工客服，让简单咨询有依据地回答，让需要人处理的问题带着上下文转交。',
    question: '小团队能不能少答一些重复问题，又不让客户在转人工后重新说一遍？',
    verified: '知识问答、人工接手及回复回传已在测试环境跑通。',
    boundary: '尚未接入真实电商客服渠道，未验证生产稳定性或实际节省的人工。',
    tools: ['飞书 / Lark', 'Dify', 'FastAPI', 'GLM辅助提示词'],
  },
  {
    slug: 'ai-website',
    number: '001',
    title: 'AI能做出官网，交付还需要一次验收。',
    shortTitle: 'AI建站：一次模拟官网交付',
    description: 'DeepSeek整理需求，Kimi提供UI方案，Codex编写代码，老鸽负责项目指挥与验收。记录本地官网演示与图片上传状态问题。',
    status: '模拟需求 · 本地运行验证',
    tags: ['AI建站', '需求拆解', '项目验收'],
    summary: '让三个AI分别参与需求、设计和开发，再以项目交付的方式检查结果，而不是停在“页面生成了”。',
    question: 'AI能不能做出一个像模像样的官网？生成之后，还需要人检查什么？',
    verified: '模拟官网已在本地运行展示；图片上传后的状态残留问题已修复。',
    boundary: '没有公开在线演示，不代表真实客户交付；未提供生产部署及真实业务使用的验证记录。',
    tools: ['DeepSeek', 'Kimi', 'Codex'],
  },
];
